
import { InMemoryDbService, InMemoryBackendConfig } from 'angular-in-memory-web-api';
import { IVehicle } from './../vehicle';

export class MockData implements InMemoryDbService, InMemoryBackendConfig {
    createDb() {

        // Vehicle Status
        let carLogs: IVehicle[] = [
            {
                amps: "11.1",
                car_name: "eVan-2",
                credit: "0.11",
                energy_charge: "35.34",
                energy_empty: "2.66",
                evse_id: "M00032",
                evse_name: "AutoPort",
                iso_id: "Charge Only",
                miles: "93.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "2.71",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "93.00",
                soc_kwh: "35.34",
                status: "NC:",
                timestamp: "2017-04-21T11:54:56Z",
                vin: "1FTNE24L65HB41008",
                volts: "244.0"
            },
            {
                amps: "-7.0",
                car_name: "Unassigned-cvorg-sim1",
                credit: "0.0",
                energy_charge: "17.85",
                energy_empty: "17.15",
                evse_id: "UDL0003",
                evse_name: "CVORG Lab 1",
                iso_id: "Not in ISO Market",
                miles: "51.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "-1.46",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "51.00",
                soc_kwh: "17.85",
                status: "NC:",
                timestamp: "2014-03-10T18:28:55Z",
                vin: "cvorg-sim1",
                volts: "208.0"
            },
            {
                amps: "0.0",
                car_name: "Honda-1",
                credit: "5.43",
                energy_charge: "6.70",
                energy_empty: "3.30",
                evse_id: "M00071",
                evse_name: "Honda V2G EVSE 1",
                iso_id: "Charge Only",
                miles: "67.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "0.0",
                power_provided: "",
                power_requested: "",
                primary_status: "GI",
                secondary_status: "",
                soc: "67.00",
                soc_kwh: "6.70",
                status: "NC:",
                timestamp: "2016-05-18T03:09:32Z",
                vin: "JHMCR5F77EC000005",
                volts: "1.0"
            },
            {
                amps: "-6.0",
                car_name: "UD-210",
                credit: "1.7",
                energy_charge: "32.90",
                energy_empty: "2.10",
                evse_id: "M00056",
                evse_name: "UD Graham Lot 53 A",
                iso_id: "PJM",
                miles: "94.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "-1.25",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "94.00",
                soc_kwh: "32.90",
                status: "SLP",
                timestamp: "2017-04-13T19:03:28Z",
                vin: "JTLKT334364060019",
                volts: "209.0"
            },
            {
                amps: "-0.3",
                car_name: "UD-170",
                credit: "108.09",
                energy_charge: "26.95",
                energy_empty: "8.05",
                evse_id: "M00056",
                evse_name: "UD Graham Lot 53 A",
                iso_id: "PJM",
                miles: "77.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "-0.06",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "77.00",
                soc_kwh: "26.95",
                status: "NC:",
                timestamp: "2017-02-08T16:18:14Z",
                vin: "JTLKT334864127858",
                volts: "204.0"
            },
            {
                amps: "-2.1",
                car_name: "DTU-eBox-1",
                credit: "",
                energy_charge: "28.70",
                energy_empty: "6.30",
                evse_id: "UDE0007",
                evse_name: "DTU-Milbank-1",
                iso_id: "Charge Only",
                miles: "82.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "-0.48",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "82.00",
                soc_kwh: "28.70",
                status: "NC:",
                timestamp: "2015-03-17T15:41:47Z",
                vin: "JTLKT334954000146",
                volts: "228.0"
            },
            {
                amps: "-63.5",
                car_name: "UD-296",
                credit: "7.17",
                energy_charge: "32.55",
                energy_empty: "2.45",
                evse_id: "UDE00004",
                evse_name: "UD-Motorpool-03",
                iso_id: "PJM",
                miles: "93.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "-13.08",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "93.00",
                soc_kwh: "32.55",
                status: "NC:",
                timestamp: "2017-04-24T19:34:00Z",
                vin: "JTLKT334964103780",
                volts: "206.0"
            },
            {
                amps: "-32.0",
                car_name: "SimulatedCar-1",
                credit: "0.0",
                energy_charge: "11.55",
                energy_empty: "23.45",
                evse_id: "evse0",
                evse_name: "",
                iso_id: "Charge Only",
                miles: "33.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "-6.66",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "33.00",
                soc_kwh: "11.55",
                status: "NC:",
                timestamp: "2015-07-02T15:08:23Z",
                vin: "sim0",
                volts: "208.0"
            },
            {
                amps: "-50.0",
                car_name: "SimulatedCar-2",
                credit: "20.25",
                energy_charge: "35.00",
                energy_empty: "0.00",
                evse_id: "evse1",
                evse_name: "",
                iso_id: "Not in ISO Market",
                miles: "100.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "-10.40",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "100.00",
                soc_kwh: "35.00",
                status: "NC:",
                timestamp: "2015-10-14T21:21:25Z",
                vin: "sim1",
                volts: "208.0"
            },
            {
                amps: "-50.0",
                car_name: "SimulatedCar-3",
                credit: "26.19",
                energy_charge: "35.00",
                energy_empty: "0.00",
                evse_id: "evse2",
                evse_name: "",
                iso_id: "Not in ISO Market",
                miles: "100.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "-10.40",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "100.00",
                soc_kwh: "35.00",
                status: "NC:",
                timestamp: "2015-10-14T21:21:25Z",
                vin: "sim2",
                volts: "208.0"
            },
            {
                amps: "-37.0",
                car_name: "Unassigned-sim3",
                credit: "0.0",
                energy_charge: "4.76",
                energy_empty: "2.24",
                evse_id: "UDL00001",
                evse_name: "Sachin's Lab EVSE",
                iso_id: "Charge Only",
                miles: "68.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "-7.70",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "68.00",
                soc_kwh: "4.76",
                status: "NC:",
                timestamp: "2015-08-07T16:41:10Z",
                vin: "sim3",
                volts: "208.0"
            },
            {
                amps: "-23.0",
                car_name: "Unassigned-sim4",
                credit: "0.76",
                energy_charge: "21.00",
                energy_empty: "14.00",
                evse_id: "evse4",
                evse_name: "",
                iso_id: "Not in ISO Market",
                miles: "60.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "-4.78",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "60.00",
                soc_kwh: "21.00",
                status: "NC:",
                timestamp: "2014-03-10T13:41:02Z",
                vin: "sim4",
                volts: "208.0"
            },
            {
                amps: "3.0",
                car_name: "MiniE-090",
                credit: "1.05",
                energy_charge: "29.05",
                energy_empty: "5.95",
                evse_id: "UDE00010",
                evse_name: "UD-Perkins-1",
                iso_id: "PJM",
                miles: "83.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "0.64",
                power_provided: "",
                power_requested: "",
                primary_status: "IA",
                secondary_status: "",
                soc: "83.00",
                soc_kwh: "29.05",
                status: "NC:",
                timestamp: "2016-09-09T15:24:15Z",
                vin: "WMWMF74508TK95302",
                volts: "212.0"
            },
            {
                amps: "0.0",
                car_name: "MINIE-243",
                credit: "34.04",
                energy_charge: "26.95",
                energy_empty: "8.05",
                evse_id: "M00009",
                evse_name: "UD-STAR-09",
                iso_id: "PJM",
                miles: "77.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "0.0",
                power_provided: "",
                power_requested: "",
                primary_status: "IA",
                secondary_status: "",
                soc: "77.00",
                soc_kwh: "26.95",
                status: "NC:",
                timestamp: "2016-02-12T03:02:44Z",
                vin: "WMWMF74508TK95459",
                volts: "242.0"
            },
            {
                amps: "-6.0",
                car_name: "MINIE-424",
                credit: "0.0",
                energy_charge: "35.00",
                energy_empty: "0.00",
                evse_id: "M00032",
                evse_name: "AutoPort",
                iso_id: "Charge Only",
                miles: "100.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "-1.50",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "100.00",
                soc_kwh: "35.00",
                status: "NC:",
                timestamp: "2016-06-10T19:53:53Z",
                vin: "WMWMF74508TK95672",
                volts: "250.0"
            },
            {
                amps: "4.0",
                car_name: "MiniE-138",
                credit: "0.01",
                energy_charge: "30.45",
                energy_empty: "4.55",
                evse_id: "M000025",
                evse_name: "PJM-Inside",
                iso_id: "Not in ISO Market",
                miles: "87.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "0.86",
                power_provided: "",
                power_requested: "",
                primary_status: "GI",
                secondary_status: "",
                soc: "87.00",
                soc_kwh: "30.45",
                status: "NC:",
                timestamp: "2014-01-21T17:12:02Z",
                vin: "WMWMF74518TK95342",
                volts: "215.0"
            },
            {
                amps: "0.0",
                car_name: "Test-Car",
                credit: "0.0",
                energy_charge: "11.90",
                energy_empty: "23.10",
                evse_id: "UDE0002",
                evse_name: "",
                iso_id: "Not in ISO Market",
                miles: "34.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "0.0",
                power_provided: "",
                power_requested: "",
                primary_status: "SLP",
                secondary_status: "",
                soc: "34.00",
                soc_kwh: "11.90",
                status: "NC:",
                timestamp: "2013-04-16T18:34:34Z",
                vin: "WMWMF74528TK95001",
                volts: "208.0"
            },
            {
                amps: "-8.0",
                car_name: "MiniE-013",
                credit: "39.47",
                energy_charge: "25.20",
                energy_empty: "9.80",
                evse_id: "M00012",
                evse_name: "UD-STAR-12",
                iso_id: "PJM",
                miles: "72.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "-1.94",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "72.00",
                soc_kwh: "25.20",
                status: "NC:",
                timestamp: "2016-10-27T15:29:58Z",
                vin: "WMWMF74528TK95284",
                volts: "242.0"
            },
            {
                amps: "1.0",
                car_name: "MiniE-207",
                credit: "39.2",
                energy_charge: "23.80",
                energy_empty: "11.20",
                evse_id: "M00010",
                evse_name: "UD-STAR-10",
                iso_id: "PJM",
                miles: "68.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "0.24",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "68.00",
                soc_kwh: "23.80",
                status: "NC:",
                timestamp: "2016-09-04T18:05:58Z",
                vin: "WMWMF74528TK95401",
                volts: "243.0"
            },
            {
                amps: "0.0",
                car_name: "EV-Grid MiniE",
                credit: "0.0",
                energy_charge: "24.50",
                energy_empty: "10.50",
                evse_id: "",
                evse_name: "",
                iso_id: "Charge Only",
                miles: "70.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "0.0",
                power_provided: "",
                power_requested: "",
                primary_status: "IA",
                secondary_status: "",
                soc: "70.00",
                soc_kwh: "24.50",
                status: "NC:",
                timestamp: "2014-06-11T21:27:52Z",
                vin: "WMWMF74538TK95225",
                volts: "241.0"
            },
            {
                amps: "0.0",
                car_name: "MiniE-089",
                credit: "127.98",
                energy_charge: "0.00",
                energy_empty: "0.00",
                evse_id: "M00002",
                evse_name: "UD-STAR-02",
                iso_id: "Not in ISO Market",
                miles: "0.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "0.0",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "0.00",
                soc_kwh: "0.00",
                status: "NC:",
                timestamp: "2016-07-01T21:41:05Z",
                vin: "WMWMF74538TK95259",
                volts: "0.0"
            },
            {
                amps: "-25.0",
                car_name: "sim00003-???",
                credit: "0.0",
                energy_charge: "17.85",
                energy_empty: "17.15",
                evse_id: "evse00003",
                evse_name: "SIM-EVSE-1",
                iso_id: "Charge Only",
                miles: "51.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "-5.20",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "51.00",
                soc_kwh: "17.85",
                status: "NC:",
                timestamp: "2015-12-02T15:24:28Z",
                vin: "sim00003",
                volts: "208.0"
            },
            {
                amps: "4.0",
                car_name: "MiniE-159",
                credit: "37.81",
                energy_charge: "35.00",
                energy_empty: "0.00",
                evse_id: "M00024",
                evse_name: "UD-Lewes-B",
                iso_id: "PJM",
                miles: "100.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "1.00",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "100.00",
                soc_kwh: "35.00",
                status: "NC:",
                timestamp: "2016-07-21T06:21:06Z",
                vin: "WMWMF74538TK95441",
                volts: "249.0"
            },
            {
                amps: "25.0",
                car_name: "MiniE-187",
                credit: "18.75",
                energy_charge: "22.75",
                energy_empty: "12.25",
                evse_id: "M00008",
                evse_name: "UD-STAR-08",
                iso_id: "PJM",
                miles: "65.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "6.12",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "65.00",
                soc_kwh: "22.75",
                status: "NC:",
                timestamp: "2016-03-15T16:07:59Z",
                vin: "WMWMF74538TK95469",
                volts: "245.0"
            },
            {
                amps: "45.0",
                car_name: "MiniE-328",
                credit: "0.0",
                energy_charge: "35.00",
                energy_empty: "0.00",
                evse_id: "M00036",
                evse_name: "ICETEC",
                iso_id: "PJM",
                miles: "100.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "10.94",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "100.00",
                soc_kwh: "35.00",
                status: "NC:",
                timestamp: "2015-12-17T06:50:57Z",
                vin: "WMWMF74538TK95505",
                volts: "243.0"
            },
            {
                amps: "0.0",
                car_name: "MiniE-487",
                credit: "39.88",
                energy_charge: "25.55",
                energy_empty: "9.45",
                evse_id: "M00013",
                evse_name: "UD-STAR-13",
                iso_id: "PJM",
                miles: "73.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "0.0",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "73.00",
                soc_kwh: "25.55",
                status: "NC:",
                timestamp: "2016-02-03T15:51:13Z",
                vin: "WMWMF74558TK95344",
                volts: "245.0"
            },
            {
                amps: "-36.0",
                car_name: "ACP MiniE",
                credit: "0.1",
                energy_charge: "29.05",
                energy_empty: "5.95",
                evse_id: "M00019",
                evse_name: "ACP1",
                iso_id: "Not in ISO Market",
                miles: "83.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "-7.42",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "83.00",
                soc_kwh: "29.05",
                status: "NC:",
                timestamp: "2014-04-10T23:38:29Z",
                vin: "WMWMF74558TK95408",
                volts: "206.0"
            },
            {
                amps: "0.0",
                car_name: "MINIE-491",
                credit: "39.46",
                energy_charge: "31.15",
                energy_empty: "3.85",
                evse_id: "M00014",
                evse_name: "UD-STAR-14",
                iso_id: "PJM",
                miles: "89.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "0.0",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "89.00",
                soc_kwh: "31.15",
                status: "NC:",
                timestamp: "2016-09-02T21:18:31Z",
                vin: "WMWMF74558TK95554",
                volts: "246.0"
            },
            {
                amps: "1.0",
                car_name: "MINIE-451",
                credit: "39.19",
                energy_charge: "25.55",
                energy_empty: "9.45",
                evse_id: "M00007",
                evse_name: "UD-STAR-07",
                iso_id: "PJM",
                miles: "73.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "0.24",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "73.00",
                soc_kwh: "25.55",
                status: "NC:",
                timestamp: "2016-02-28T12:50:06Z",
                vin: "WMWMF74558TK95652",
                volts: "242.0"
            },
            {
                amps: "-4.0",
                car_name: "MiniE-072",
                credit: "",
                energy_charge: "35.00",
                energy_empty: "0.00",
                evse_id: "M00073",
                evse_name: "M000073",
                iso_id: "Not in ISO Market",
                miles: "100.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "-1.02",
                power_provided: "",
                power_requested: "",
                primary_status: "SLP",
                secondary_status: "",
                soc: "100.00",
                soc_kwh: "35.00",
                status: "NC:",
                timestamp: "2015-11-11T16:27:20Z",
                vin: "WMWMF74568TK95305",
                volts: "254.0"
            },
            {
                amps: "0.0",
                car_name: "MiniE-008",
                credit: "0.0",
                energy_charge: "35.00",
                energy_empty: "0.00",
                evse_id: "M00063",
                evse_name: "M0000063",
                iso_id: "PJM",
                miles: "100.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "0.0",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "100.00",
                soc_kwh: "35.00",
                status: "NC:",
                timestamp: "2015-07-17T15:31:12Z",
                vin: "WMWMF74578TK95216",
                volts: "249.0"
            },
            {
                amps: "-6.0",
                car_name: "MiniE-165",
                credit: "31.12",
                energy_charge: "35.00",
                energy_empty: "0.00",
                evse_id: "M00027",
                evse_name: "Kempton EVSE",
                iso_id: "PJM",
                miles: "100.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "-1.50",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "100.00",
                soc_kwh: "35.00",
                status: "NC:",
                timestamp: "2016-09-02T06:18:53Z",
                vin: "WMWMF74578TK95314",
                volts: "250.0"
            },
            {
                amps: "-88.0",
                car_name: "MINIE-478",
                credit: "38.15",
                energy_charge: "8.05",
                energy_empty: "26.95",
                evse_id: "M00004",
                evse_name: "UD-STAR-04",
                iso_id: "PJM",
                miles: "23.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "-20.15",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "23.00",
                soc_kwh: "8.05",
                status: "NC:",
                timestamp: "2016-09-09T14:57:13Z",
                vin: "WMWMF74578TK95670",
                volts: "229.0"
            },
            {
                amps: "0.0",
                car_name: "MiniE-023",
                credit: "32.34",
                energy_charge: "35.00",
                energy_empty: "0.00",
                evse_id: "M00026",
                evse_name: "UD-Robinson-2",
                iso_id: "PJM",
                miles: "100.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "0.0",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "100.00",
                soc_kwh: "35.00",
                status: "NC:",
                timestamp: "2016-09-06T17:48:37Z",
                vin: "WMWMF74588TK95239",
                volts: "207.0"
            },
            {
                amps: "2.0",
                car_name: "MiniE-366",
                credit: "91.87",
                energy_charge: "28.35",
                energy_empty: "6.65",
                evse_id: "M000002",
                evse_name: "",
                iso_id: "Not in ISO Market",
                miles: "81.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "0.49",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "81.00",
                soc_kwh: "28.35",
                status: "NC:",
                timestamp: "2013-10-14T18:53:40Z",
                vin: "WMWMF74588TK95581",
                volts: "245.0"
            },
            {
                amps: "0.0",
                car_name: "MiniE-082",
                credit: "39.59",
                energy_charge: "30.45",
                energy_empty: "4.55",
                evse_id: "M00008",
                evse_name: "UD-STAR-08",
                iso_id: "PJM",
                miles: "87.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "0.0",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "87.00",
                soc_kwh: "30.45",
                status: "NC:",
                timestamp: "2015-08-11T16:32:56Z",
                vin: "WMWMF74598TK95265",
                volts: "0.0"
            },
            {
                amps: "1.0",
                car_name: "MiniE-171",
                credit: "49.14",
                energy_charge: "19.60",
                energy_empty: "15.40",
                evse_id: "M00001",
                evse_name: "UD-STAR-01",
                iso_id: "PJM",
                miles: "56.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "0.24",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "56.00",
                soc_kwh: "19.60",
                status: "NC:",
                timestamp: "2016-08-18T14:58:15Z",
                vin: "WMWMF74598TK95377",
                volts: "239.0"
            },
            {
                amps: "0.0",
                car_name: "MiniE-102",
                credit: "0.49",
                energy_charge: "0.00",
                energy_empty: "0.00",
                evse_id: "M00011",
                evse_name: "UD-STAR-11",
                iso_id: "Not in ISO Market",
                miles: "0.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "0.0",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "0.00",
                soc_kwh: "0.00",
                status: "NC:",
                timestamp: "2016-08-18T14:49:01Z",
                vin: "WMWMF74598TK95394",
                volts: "0.0"
            },
            {
                amps: "0.0",
                car_name: "MiniE-267",
                credit: "6.36",
                energy_charge: "25.90",
                energy_empty: "9.10",
                evse_id: "UDE00003",
                evse_name: "UD-Motorpool-02",
                iso_id: "PJM",
                miles: "74.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "0.0",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "74.00",
                soc_kwh: "25.90",
                status: "NC:",
                timestamp: "2016-09-14T13:10:41Z",
                vin: "WMWMF74598TK95492",
                volts: "214.0"
            },
            {
                amps: "1.0",
                car_name: "MiniE-234",
                credit: "32.55",
                energy_charge: "32.20",
                energy_empty: "2.80",
                evse_id: "M00013",
                evse_name: "UD-STAR-13",
                iso_id: "PJM",
                miles: "92.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "0.24",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "92.00",
                soc_kwh: "32.20",
                status: "NC:",
                timestamp: "2016-10-21T20:50:32Z",
                vin: "WMWMF74598TK95501",
                volts: "244.0"
            },
            {
                amps: "1.0",
                car_name: "MiniE-361",
                credit: "23.75",
                energy_charge: "25.55",
                energy_empty: "9.45",
                evse_id: "UDE00005",
                evse_name: "UD-Motorpool-04",
                iso_id: "PJM",
                miles: "73.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "0.18",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "73.00",
                soc_kwh: "25.55",
                status: "NC:",
                timestamp: "2016-09-14T13:12:25Z",
                vin: "WMWMF74598TK95606",
                volts: "185.0"
            },
            {
                amps: "1.0",
                car_name: "MiniE-073",
                credit: "40.14",
                energy_charge: "32.55",
                energy_empty: "2.45",
                evse_id: "M00012",
                evse_name: "UD-STAR-12",
                iso_id: "PJM",
                miles: "93.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "0.24",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "93.00",
                soc_kwh: "32.55",
                status: "NC:",
                timestamp: "2016-09-07T17:40:17Z",
                vin: "WMWMF745X8TK95307",
                volts: "245.0"
            },
            {
                amps: "14.0",
                car_name: "MiniE-262",
                credit: "0.25",
                energy_charge: "27.65",
                energy_empty: "7.35",
                evse_id: "M00033",
                evse_name: "Service Unlimited 1",
                iso_id: "Not in ISO Market",
                miles: "79.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "3.05",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "79.00",
                soc_kwh: "27.65",
                status: "NC:",
                timestamp: "2016-01-13T21:44:57Z",
                vin: "WMWMF745X8TK95601",
                volts: "218.0"
            },
            {
                amps: "-27.3",
                car_name: "Dumb-EV@Sachin's Lab EVSE",
                credit: "0.0",
                energy_charge: "10.00",
                energy_empty: "10.00",
                evse_id: "UDL00001",
                evse_name: "Sachin's Lab EVSE",
                iso_id: "PJM",
                miles: "50.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "-5.70",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "50.00",
                soc_kwh: "10.00",
                status: "NC:",
                timestamp: "2015-10-08T14:48:38Z",
                vin: "dumb-ev:UDL00001",
                volts: "208.0"
            },
            {
                amps: "-2.0",
                car_name: "Dumb-EV@Evans-EVSE",
                credit: "0.0",
                energy_charge: "10.00",
                energy_empty: "10.00",
                evse_id: "NIC00001",
                evse_name: "Evans-EVSE",
                iso_id: "PJM",
                miles: "50.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "-0.44",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "50.00",
                soc_kwh: "10.00",
                status: "NC:",
                timestamp: "2016-02-29T17:33:17Z",
                vin: "dumb-ev:NIC00001",
                volts: "207.9"
            },
            {
                amps: "-53.0",
                car_name: "MiniE-465",
                credit: "0.0",
                energy_charge: "18.20",
                energy_empty: "16.80",
                evse_id: "M00062",
                evse_name: "M0000062",
                iso_id: "PJM",
                miles: "52.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "-12.35",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "52.00",
                soc_kwh: "18.20",
                status: "NC:",
                timestamp: "2016-07-30T18:02:08Z",
                vin: "WMWMF74508TK95610",
                volts: "233.0"
            },
            {
                amps: "-0.5",
                car_name: "D00001",
                credit: "0.0",
                energy_charge: "12.80",
                energy_empty: "7.20",
                evse_id: "M00005",
                evse_name: "UD-STAR-05",
                iso_id: "Not in ISO Market",
                miles: "64.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "-0.14",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "64.00",
                soc_kwh: "12.80",
                status: "NC:",
                timestamp: "2016-08-19T22:53:45Z",
                vin: "D00001",
                volts: "241.0"
            },
            {
                amps: "-25.0",
                car_name: "sim00002-???",
                credit: "0.0",
                energy_charge: "17.85",
                energy_empty: "17.15",
                evse_id: "evse00002",
                evse_name: "SIM-EVSE-1",
                iso_id: "Charge Only",
                miles: "51.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "-5.20",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "51.00",
                soc_kwh: "17.85",
                status: "NC:",
                timestamp: "2015-12-02T15:24:28Z",
                vin: "sim00002",
                volts: "208.0"
            },
            {
                amps: "-25.0",
                car_name: "sim00001-???",
                credit: "0.0",
                energy_charge: "17.85",
                energy_empty: "17.15",
                evse_id: "evse00001",
                evse_name: "SIM-EVSE-1",
                iso_id: "Charge Only",
                miles: "51.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "-5.20",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "51.00",
                soc_kwh: "17.85",
                status: "NC:",
                timestamp: "2015-12-02T15:24:26Z",
                vin: "sim00001",
                volts: "208.0"
            },
            {
                amps: "2.0",
                car_name: "MINI E-297",
                credit: "0.0",
                energy_charge: "35.00",
                energy_empty: "0.00",
                evse_id: "M00043",
                evse_name: "Spirae 2",
                iso_id: "Charge Only",
                miles: "100.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "0.45",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "100.00",
                soc_kwh: "35.00",
                status: "NC:",
                timestamp: "2015-10-16T17:01:59Z",
                vin: "WMWMF74538TK95570",
                volts: "226.0"
            },
            {
                amps: "0.0",
                car_name: "MINI E-282",
                credit: "",
                energy_charge: "34.65",
                energy_empty: "0.35",
                evse_id: "M00032",
                evse_name: "AutoPort",
                iso_id: "Charge Only",
                miles: "99.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "0.0",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "99.00",
                soc_kwh: "34.65",
                status: "NC:",
                timestamp: "2016-08-26T15:40:10Z",
                vin: "WMWMF74538TK95438",
                volts: "251.0"
            },
            {
                amps: "-19.0",
                car_name: "Mini E-284",
                credit: "0.0",
                energy_charge: "35.00",
                energy_empty: "0.00",
                evse_id: "M00053",
                evse_name: "",
                iso_id: "Charge Only",
                miles: "100.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "-4.01",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "100.00",
                soc_kwh: "35.00",
                status: "NC:",
                timestamp: "2015-10-16T16:03:33Z",
                vin: "WMWMF74538TK95578",
                volts: "211.0"
            },
            {
                amps: "1.0",
                car_name: "MiniE-331",
                credit: "0.0",
                energy_charge: "26.60",
                energy_empty: "8.40",
                evse_id: "M00044",
                evse_name: "NRG Smart Home",
                iso_id: "Charge Only",
                miles: "76.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "0.25",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "76.00",
                soc_kwh: "26.60",
                status: "NC:",
                timestamp: "2015-11-19T19:32:00Z",
                vin: "WMWMF74528TK95527",
                volts: "249.0"
            },
            {
                amps: "0.0",
                car_name: "MiniE-052",
                credit: "",
                energy_charge: "0.00",
                energy_empty: "0.00",
                evse_id: "",
                evse_name: "",
                iso_id: "Not in ISO Market",
                miles: "0.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "0.0",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "0.00",
                soc_kwh: "0.00",
                status: "NC:",
                timestamp: "1970-01-01T00:00:00Z",
                vin: "WMWMF74588TK95306",
                volts: "0.0"
            },
            {
                amps: "36.7",
                car_name: "UD-Leaf-1",
                credit: "0.0",
                energy_charge: "15.80",
                energy_empty: "6.60",
                evse_id: "PP-0001",
                evse_name: "Princeton-Power-1",
                iso_id: "PJM",
                miles: "70.54",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "10.40",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "70.54",
                soc_kwh: "15.80",
                status: "NC:",
                timestamp: "2016-07-20T22:55:10Z",
                vin: "PP-0001",
                volts: "283.1"
            },
            {
                amps: "0.0",
                car_name: "EV@Princeton-Power-2",
                credit: "0.0",
                energy_charge: "-1.00",
                energy_empty: "0.00",
                evse_id: "PP-0002",
                evse_name: "Princeton-Power-2",
                iso_id: "PJM",
                miles: "0.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "0.0",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "0.00",
                soc_kwh: "-1.00",
                status: "NC:",
                timestamp: "2016-01-10T23:59:00Z",
                vin: "PP-0002",
                volts: "118.3"
            },
            {
                amps: "-31.3",
                car_name: "Postal Truck",
                credit: "0.0",
                energy_charge: "32.30",
                energy_empty: "5.70",
                evse_id: "M00032",
                evse_name: "AutoPort",
                iso_id: "Charge Only",
                miles: "85.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "-7.48",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "85.00",
                soc_kwh: "32.30",
                status: "NC:",
                timestamp: "2016-05-10T11:56:04Z",
                vin: "1GBCS10A6N2912184",
                volts: "239.0"
            },
            {
                amps: "0.0",
                car_name: "JTLK334664038015-???",
                credit: "",
                energy_charge: "39.90",
                energy_empty: "-4.90",
                evse_id: "UDE00002",
                evse_name: "UD-Motorpool-01",
                iso_id: "PJM",
                miles: "114.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "0.0",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "114.00",
                soc_kwh: "39.90",
                status: "NC:",
                timestamp: "2017-04-25T22:30:58Z",
                vin: "JTLK334664038015",
                volts: "0.0"
            },
            {
                amps: "0.0",
                car_name: "Mini E-085",
                credit: "0.0",
                energy_charge: "0.00",
                energy_empty: "0.00",
                evse_id: "M00039",
                evse_name: "Wiliams EVSE",
                iso_id: "Not in ISO Market",
                miles: "0.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "0.0",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "0.00",
                soc_kwh: "0.00",
                status: "NC:",
                timestamp: "2016-08-23T19:12:52Z",
                vin: "WMWMF74508TK95249",
                volts: "0.0"
            },
            {
                amps: "0.0",
                car_name: "Torrance-Bus-1",
                credit: "0.0",
                energy_charge: "0.00",
                energy_empty: "0.00",
                evse_id: "UDE00011",
                evse_name: "Transpower-1",
                iso_id: "Not in ISO Market",
                miles: "0.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "0.0",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "0.00",
                soc_kwh: "0.00",
                status: "NC:",
                timestamp: "2016-02-05T00:03:31Z",
                vin: "1HVBBAAM2TH329339",
                volts: "0.0"
            },
            {
                amps: "0.0",
                car_name: "UD-Facilties-eBox",
                credit: "0.0",
                energy_charge: "32.00",
                energy_empty: "0.00",
                evse_id: "UDE00002",
                evse_name: "UD-Motorpool-01",
                iso_id: "PJM",
                miles: "100.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "0.0",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "100.00",
                soc_kwh: "32.00",
                status: "NC:",
                timestamp: "2017-04-26T21:54:08Z",
                vin: "JTLKT334040162852",
                volts: "0.0"
            },
            {
                amps: "-15.7",
                car_name: "UD-356",
                credit: "",
                energy_charge: "32.90",
                energy_empty: "2.10",
                evse_id: "M00026",
                evse_name: "UD-Robinson-2",
                iso_id: "PJM",
                miles: "94.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "-3.23",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "94.00",
                soc_kwh: "32.90",
                status: "NC:",
                timestamp: "2017-04-13T17:10:20Z",
                vin: "JTLKT334254021923",
                volts: "206.0"
            },
            {
                amps: "-4.6",
                car_name: "Honda-3",
                credit: "0.0",
                energy_charge: "6.80",
                energy_empty: "3.20",
                evse_id: "M00071",
                evse_name: "Honda V2G EVSE 1",
                iso_id: "Charge Only",
                miles: "68.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "-1.15",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "68.00",
                soc_kwh: "6.80",
                status: "NC:",
                timestamp: "2016-05-18T03:40:20Z",
                vin: "JHMCR5F77EC000061",
                volts: "245.0"
            },
            {
                amps: "-4.5",
                car_name: "Honda-5",
                credit: "0.0",
                energy_charge: "6.50",
                energy_empty: "3.50",
                evse_id: "M00071",
                evse_name: "Honda V2G EVSE 1",
                iso_id: "Charge Only",
                miles: "65.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "-1.12",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "65.00",
                soc_kwh: "6.50",
                status: "NC:",
                timestamp: "2016-05-18T02:07:48Z",
                vin: "JHMCR5F77EC000064",
                volts: "246.0"
            },
            {
                amps: "-0.1",
                car_name: "Honda-test-unit",
                credit: "0.0",
                energy_charge: "6.50",
                energy_empty: "3.50",
                evse_id: "M00071",
                evse_name: "Honda V2G EVSE 1",
                iso_id: "Charge Only",
                miles: "65.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "-0.04",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "65.00",
                soc_kwh: "6.50",
                status: "NC:",
                timestamp: "2016-05-18T04:20:42Z",
                vin: "JHMCR5F77EC000065",
                volts: "248.0"
            },
            {
                amps: "0.0",
                car_name: "Dumb-EV@UD Graham Lot 53 A",
                credit: "0.0",
                energy_charge: "11.80",
                energy_empty: "-1.80",
                evse_id: "",
                evse_name: "",
                iso_id: "Charge Only",
                miles: "118.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "0.0",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "118.00",
                soc_kwh: "11.80",
                status: "NC:",
                timestamp: "2016-06-25T19:29:09Z",
                vin: "M00056",
                volts: "208.0"
            },
            {
                amps: "-3.0",
                car_name: "Dumb-EV@UD Graham Lot53 C",
                credit: "0.0",
                energy_charge: "13.20",
                energy_empty: "-3.20",
                evse_id: "M00055",
                evse_name: "UD Graham Lot53 C",
                iso_id: "PJM",
                miles: "132.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "-0.64",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "132.00",
                soc_kwh: "13.20",
                status: "NC:",
                timestamp: "2016-06-24T16:59:01Z",
                vin: "M00055",
                volts: "208.3"
            },
            {
                amps: "0.0",
                car_name: "Honda Accord V2G 3",
                credit: "0.0",
                energy_charge: "0.00",
                energy_empty: "0.00",
                evse_id: "M00069",
                evse_name: "NREL-1",
                iso_id: "Not in ISO Market",
                miles: "0.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "0.0",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "0.00",
                soc_kwh: "0.00",
                status: "NC:",
                timestamp: "2017-02-16T22:08:38Z",
                vin: "JHMCR5F75EC000150",
                volts: "0.0"
            },
            {
                amps: "-1.9",
                car_name: "Honda Accord V2G 2",
                credit: "0.0",
                energy_charge: "3.85",
                energy_empty: "1.15",
                evse_id: "M00041",
                evse_name: "UCSD P703-2",
                iso_id: "UCSD",
                miles: "77.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "-0.48",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "77.00",
                soc_kwh: "3.85",
                status: "NC:",
                timestamp: "2017-02-07T03:02:02Z",
                vin: "JHMCR5F78EC000286",
                volts: "248.0"
            },
            {
                amps: "0.0",
                car_name: "Dumb-EV@UCSD P703-2",
                credit: "0.0",
                energy_charge: "12.30",
                energy_empty: "7.70",
                evse_id: "M00041",
                evse_name: "UCSD P703-2",
                iso_id: "UCSD",
                miles: "61.50",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "0.0",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "61.50",
                soc_kwh: "12.30",
                status: "NC:",
                timestamp: "2017-04-04T19:22:15Z",
                vin: "dumb-ev:M00041",
                volts: "245.9"
            },
            {
                amps: "0.0",
                car_name: "Dumb-EV@UCSD P703-1",
                credit: "0.0",
                energy_charge: "10.00",
                energy_empty: "10.00",
                evse_id: "",
                evse_name: "",
                iso_id: "Charge Only",
                miles: "50.00",
                peer_connected: "false",
                pop: "",
                power_capacity_down: "",
                power_capacity_up: "",
                power_flow: "0.0",
                power_provided: "",
                power_requested: "",
                primary_status: "NC",
                secondary_status: "",
                soc: "50.00",
                soc_kwh: "10.00",
                status: "NC:",
                timestamp: "2016-12-22T09:06:00Z",
                vin: "dumb-ev:M00031",
                volts: "246.3"
            }
        ]

        return { carLogs: carLogs };
    }
}
